// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI8ccOol4gKqXLWn9pcQ29zfX65STMg0Q',
    appId: '1:219647329734:android:ae0066fe61ed6df756dec7',
    messagingSenderId: '219647329734',
    projectId: 'inam-motors',
    storageBucket: 'inam-motors.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfecO1aU1EMbtZr5r1IQm8PDTdgtdxs00',
    appId: '1:219647329734:ios:693feb20a7cde8c456dec7',
    messagingSenderId: '219647329734',
    projectId: 'inam-motors',
    storageBucket: 'inam-motors.firebasestorage.app',
    iosBundleId: 'com.inammotors.syste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfecO1aU1EMbtZr5r1IQm8PDTdgtdxs00',
    appId: '1:219647329734:ios:aee0df219ec3b05556dec7',
    messagingSenderId: '219647329734',
    projectId: 'inam-motors',
    storageBucket: 'inam-motors.firebasestorage.app',
    iosBundleId: 'com.inammotors.sys',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw-T51-9u4AMa0Ac5HBl2jN7JXorCQ4W8',
    appId: '1:219647329734:web:de334ab77466a85956dec7',
    messagingSenderId: '219647329734',
    projectId: 'inam-motors',
    authDomain: 'inam-motors.firebaseapp.com',
    storageBucket: 'inam-motors.firebasestorage.app',
  );

}